language: node_js
node_js:
  - 13

services:
  - docker
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker built -t $DOCKERHUB_USERNAME/udagram-api-feed:v1 ./udagram-api-feed
  - docker built -t $DOCKERHUB_USERNAME/udagram-api-user:v1 ./udagram-api-user
  - docker built -t $DOCKERHUB_USERNAME/udagram-frontend:v1 ./udagram-api-frontend
  - docker built -t $DOCKERHUB_USERNAME/udagram-reverseproxy:v1 ./udagram-reverseproxy
  - docker push $DOCKERHUB_USERNAME/udagram-api-feed:v1
  - docker push $DOCKERHUB_USERNAME/udagram-api-user:v1
  - docker push $DOCKERHUB_USERNAME/udagram-frontend:v1
  - docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:v1